#!/bin/sh

echo "$0 | $1"
ver_start=`sed -n "s/^\([0-9]\+\)\.\([0-9]\+\)\.[0-9]\+\.[0-9]\+$/\1.\2./gp" $1`
ver_num=`sed -n "s/^[0-9]\+\.[0-9]\+\.\([0-9]\+\)\.[0-9]\+$/\1/gp" $1`
ver_num=`expr $ver_num + 1`
echo "$ver_start$ver_num."`date +%s` > $1
